#!/usr/bin/python3

import subprocess
import xml.etree.ElementTree as ET


def repo_changes(repo, since):
    changes = ''
    out = subprocess.check_output(
        ['git', 'log', '%s..HEAD' % since], cwd='../' + repo).decode()

    commit = None
    in_image_update = False
    for line in out.splitlines():
        if line.startswith('commit '):
            if not commit:
                commit = line.split()[1]
            in_image_update = False
        elif line.startswith('    Alpine Base Updates:'):
            in_image_update = True

        if in_image_update:
            line = line[4:]
            if not line.startswith('Signed-off-by:'):
                changes += line + '\n'

    return commit, changes


def main():
    tree = ET.parse('default.xml')
    root = tree.getroot()

    commit_msg = ''
    for p in root.findall('project'):
        new_sha, changes = repo_changes(p.attrib['name'], p.attrib['revision'])
        if new_sha:
            commit_msg += '# %s\n%s\n' % (p.attrib['name'], changes)
            p.attrib['revision'] = new_sha

    if commit_msg:
        tree.write('default.xml')
        commit_msg = 'Bump container versions\n\n' + commit_msg
        subprocess.check_call(
            ['git', 'commit', '--signoff', 'default.xml', '-m', commit_msg])


if __name__ == '__main__':
    import os
    os.chdir(os.path.dirname(__file__))
    main()
